#!/usr/bin/env bash
# nginx load balancer for multiple local vLLM instances.
#
# Layout (default):
#   nginx listen 127.0.0.1:8001  ->  SSH LocalForward 8001 (CPU eval sees one API)
#   vLLM backends 127.0.0.1:8010,8011,...  (NUM_INSTANCES, one GPU each)
#
# Sticky routing (default, scheme 2):
#   hash $http_x_swe_instance_id → same SWE-bench instance_id always hits the same GPU
#   Agent must send header X-SWE-Instance-Id (use integrations.miniswe.run_swebench)
#
# Typical workflow:
#   1) GPU: NUM_INSTANCES=8 BASE_PORT=8010 bash scripts/serve_gemma4_12b.sh
#   2) GPU: NUM_BACKENDS=8 VLLM_BASE_PORT=8010 bash scripts/nginx_vllm_lb.sh start
#   3) CPU: VLLM_BASE=http://127.0.0.1:8001/v1 WORKERS=8 bash scripts/run_swebench_vm_docker.sh
#
# Env:
#   NGINX_LISTEN_PORT=8001
#   VLLM_BASE_PORT=8010       first vLLM port (must not equal NGINX_LISTEN_PORT)
#   NUM_BACKENDS=8
#   NGINX_LB_MODE=sticky|least_conn   default: sticky (prefix cache friendly)
#   PROXY_READ_TIMEOUT=960    seconds (8min LLM timeout + 1 retry headroom)
#   NGINX_MODE=standalone|system   standalone=project nginx.conf; system=/etc/nginx/conf.d
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

NGINX_LISTEN_PORT="${NGINX_LISTEN_PORT:-8001}"
VLLM_BASE_PORT="${VLLM_BASE_PORT:-8010}"
NUM_BACKENDS="${NUM_BACKENDS:-8}"
NGINX_LB_MODE="${NGINX_LB_MODE:-sticky}"
PROXY_READ_TIMEOUT="${PROXY_READ_TIMEOUT:-960}"
NGINX_MODE="${NGINX_MODE:-standalone}"
ACTION="${1:-start}"

GEN_DIR="$ROOT/results/nginx"
GEN_CONF="$GEN_DIR/vllm_lb.conf"
RUNTIME_DIR="$GEN_DIR/runtime"
SYSTEM_CONF="/etc/nginx/conf.d/vllm_gemma4_lb.conf"

usage() {
  cat <<EOF
Usage: bash scripts/nginx_vllm_lb.sh {start|stop|reload|status|print}

  start   Write config and start/reload nginx
  stop    Stop standalone nginx (or print system nginx hint)
  reload  Regenerate config and reload
  status  Check :${NGINX_LISTEN_PORT}/v1/models
  print   Print generated config to stdout

Env: NGINX_LISTEN_PORT VLLM_BASE_PORT NUM_BACKENDS NGINX_LB_MODE PROXY_READ_TIMEOUT NGINX_MODE
EOF
}

write_lb_conf() {
  mkdir -p "$GEN_DIR"
  {
    echo "# Auto-generated by scripts/nginx_vllm_lb.sh — do not edit manually"
    if [[ "$NGINX_LB_MODE" == "sticky" ]]; then
      cat <<'NGINX_MAP'
map $http_x_swe_instance_id $vllm_sticky_key {
    default $http_x_swe_instance_id;
    ""      $request_id;
}
NGINX_MAP
    fi
    echo "upstream vllm_gemma4 {"
    if [[ "$NGINX_LB_MODE" == "sticky" ]]; then
      echo "    hash \$vllm_sticky_key consistent;"
    else
      echo "    least_conn;"
    fi
    for ((i = 0; i < NUM_BACKENDS; i++)); do
      local port=$((VLLM_BASE_PORT + i))
      echo "    server 127.0.0.1:${port} max_fails=3 fail_timeout=30s;"
    done
    echo "}"
    echo
    echo "server {"
    echo "    listen 127.0.0.1:${NGINX_LISTEN_PORT};"
    echo "    listen ${NGINX_LISTEN_PORT};"
    echo
    echo "    proxy_connect_timeout 60s;"
    echo "    proxy_send_timeout    ${PROXY_READ_TIMEOUT}s;"
    echo "    proxy_read_timeout    ${PROXY_READ_TIMEOUT}s;"
    echo "    client_max_body_size 64m;"
    echo
    echo "    location / {"
    echo "        proxy_pass http://vllm_gemma4;"
    echo "        proxy_http_version 1.1;"
    echo "        proxy_set_header Host              \$host;"
    echo "        proxy_set_header X-Real-IP         \$remote_addr;"
    echo "        proxy_set_header Connection        \"\";"
    echo "        proxy_set_header X-Accel-Buffering no;"
    echo "        proxy_buffering off;"
    echo "        proxy_cache off;"
    echo "        chunked_transfer_encoding on;"
    echo "        add_header X-VLLM-Backend \$upstream_addr always;"
    echo "    }"
    echo "}"
  } >"$GEN_CONF"
}

ensure_nginx() {
  if command -v nginx >/dev/null 2>&1; then
    return 0
  fi
  echo "ERROR: nginx not found. Install on GPU host, e.g.:" >&2
  echo "  apt-get update && apt-get install -y nginx" >&2
  exit 1
}

start_standalone() {
  ensure_nginx
  mkdir -p "$RUNTIME_DIR/logs"
  cp "$GEN_CONF" "$RUNTIME_DIR/vllm_lb.conf"
  local main_conf="$ROOT/configs/nginx/nginx.conf"
  if [[ -f "$RUNTIME_DIR/logs/nginx.pid" ]] && kill -0 "$(cat "$RUNTIME_DIR/logs/nginx.pid")" 2>/dev/null; then
    nginx -c "$main_conf" -p "$RUNTIME_DIR" -s reload
    echo "==> Reloaded standalone nginx"
  else
    nginx -c "$main_conf" -p "$RUNTIME_DIR"
    echo "==> Started standalone nginx (prefix=$RUNTIME_DIR)"
  fi
}

stop_standalone() {
  local main_conf="$ROOT/configs/nginx/nginx.conf"
  if [[ -f "$RUNTIME_DIR/logs/nginx.pid" ]]; then
    nginx -c "$main_conf" -p "$RUNTIME_DIR" -s stop 2>/dev/null || true
    echo "==> Stopped standalone nginx"
  else
    echo "Standalone nginx not running (no pid file)"
  fi
}

start_system() {
  ensure_nginx
  sudo cp "$GEN_CONF" "$SYSTEM_CONF"
  sudo nginx -t
  sudo systemctl reload nginx 2>/dev/null || sudo nginx -s reload
  echo "==> Installed $SYSTEM_CONF and reloaded system nginx"
}

stop_system() {
  echo "To remove system config: sudo rm -f $SYSTEM_CONF && sudo nginx -s reload"
}

check_status() {
  echo "==> nginx LB http://127.0.0.1:${NGINX_LISTEN_PORT}/v1/models"
  curl -sf "http://127.0.0.1:${NGINX_LISTEN_PORT}/v1/models" | head -c 500 || {
    echo "FAILED: nginx or backends not ready" >&2
    exit 1
  }
  echo
  if [[ "$NGINX_LB_MODE" == "sticky" ]]; then
    echo "==> Sticky routing probe (same X-SWE-Instance-Id → same backend):"
    for _ in 1 2; do
      curl -sI "http://127.0.0.1:${NGINX_LISTEN_PORT}/v1/models" \
        -H "X-SWE-Instance-Id: sticky-probe-test" | grep -i x-vllm-backend || true
    done
  fi
  echo "==> vLLM backends:"
  for ((i = 0; i < NUM_BACKENDS; i++)); do
    local port=$((VLLM_BASE_PORT + i))
    if curl -sf "http://127.0.0.1:${port}/v1/models" >/dev/null 2>&1; then
      echo "    OK  :${port}"
    else
      echo "    DOWN:${port}"
    fi
  done
}

if [[ "$NGINX_LISTEN_PORT" == "$VLLM_BASE_PORT" ]] || \
   (( NGINX_LISTEN_PORT >= VLLM_BASE_PORT && NGINX_LISTEN_PORT < VLLM_BASE_PORT + NUM_BACKENDS )); then
  echo "ERROR: NGINX_LISTEN_PORT=$NGINX_LISTEN_PORT overlaps vLLM ports ${VLLM_BASE_PORT}-$((VLLM_BASE_PORT + NUM_BACKENDS - 1))" >&2
  echo "       Use e.g. NGINX_LISTEN_PORT=8001 VLLM_BASE_PORT=8010" >&2
  exit 1
fi

case "$ACTION" in
  -h|--help|help)
    usage
    exit 0
    ;;
  print)
    write_lb_conf
    cat "$GEN_CONF"
    ;;
  start)
    write_lb_conf
    echo "==> Wrote $GEN_CONF"
    echo "    nginx :${NGINX_LISTEN_PORT} -> vLLM ${VLLM_BASE_PORT}-$((VLLM_BASE_PORT + NUM_BACKENDS - 1)) (${NGINX_LB_MODE})"
    if [[ "$NGINX_MODE" == "system" ]]; then
      start_system
    else
      start_standalone
    fi
    check_status
    ;;
  reload)
    write_lb_conf
    if [[ "$NGINX_MODE" == "system" ]]; then
      start_system
    else
      start_standalone
    fi
    ;;
  stop)
    if [[ "$NGINX_MODE" == "system" ]]; then
      stop_system
    else
      stop_standalone
    fi
    ;;
  status)
    check_status
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
